# Generated by Django 6.0.4 on 2026-05-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0007_add_docs_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentrelease",
            name="global_context",
            field=models.JSONField(default=dict),
        ),
    ]
